[platformio]
src_dir = .

[env:gateway]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
board_build.filesystem = littlefs
lib_extra_dirs = ../lib
lib_deps =
    bblanchon/ArduinoJson@^6
