[platformio]
src_dir = .

[env:node]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ../lib
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library
    claws/BH1750
